# Generated by Django 4.2.7 on 2023-11-17 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_blog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="Product",
            new_name="product",
        ),
    ]
